FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/labstation-xadyr/firestore/indexes?create_composite=ClFwcm9qZWN0cy9sYWJzdGF0aW9uLXhhZHlyL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9ib29raW5ncy9pbmRleGVzL18QARoOCgpyZXNvdXJjZUlkEAEaCgoGdXNlcklkEAEaDQoJc3RhcnRUaW1lEAIaDAoIX19uYW1lX18QAg
let me know I this error is required manual intervention if not then fix it