FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/labstation-xadyr/firestore/indexes?create_composite=ClZwcm9qZWN0cy9sYWJzdGF0aW9uLXhhZHlyL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9ub3RpZmljYXRpb25zL2luZGV4ZXMvXxABGgoKBnVzZXJJZBABGg0KCWNyZWF0ZWRBdBACGgwKCF9fbmFtZV9fEAI
what is this issue man, I am frustrated by the issues related to indexes just tell me the ones I have to add. I will just add